import { useState } from "react";
import { Link } from "react-router-dom";
import { Arrow, LandingLink, Photo, SampleLabel, SectionLabel } from "./LandingPrimitives";

export function MarketSection() {
  return <section className="lp-section lp-market" id="market-information"><div data-reveal><SectionLabel number="07">A view of the market</SectionLabel><h2>Know what markets<br /><span className="lp-soft">are reporting.</span></h2><p className="lp-body">Keep the latest reported mandi price in perspective, with its market, commodity and reporting date visible together.</p><p className="lp-fine">Government of India · data.gov.in / AGMARKNET.<br />Daily wholesale reporting—not live trading, a guaranteed selling price, or a forecast.</p><LandingLink to="/farmer/market-intelligence" secondary>Explore Market Intelligence</LandingLink></div><div className="lp-market-report" data-reveal><div className="lp-report-header"><span className="lp-dot" /><span>AGMARKNET</span><span>REPORTED DATA</span></div><h3>Context before<br />the price.</h3><dl>{[["Market", "Reporting mandi"], ["Commodity", "Selected crop"], ["Min · Modal · Max", "Reported wholesale prices"], ["Report date", "Date provided by source"]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="lp-report-note">Record structure shown. No live price feed is loaded on this page.</p></div></section>;
}

const produce = [
  { name: "Tomato", image: "tomatoes", price: 40, alt: "Fresh red tomatoes with droplets against a dark background" },
  { name: "Mango", image: "mangoes", price: 70, alt: "Close-up of ripe yellow and red mangoes" },
  { name: "Strawberry", image: "strawberries", price: 150, alt: "Fresh red strawberries with green stems" },
];

export function MarketplaceSection() {
  const [angle, setAngle] = useState(0);
  const views = [{ image: "tomatoes", label: "Close-up" }, { image: "tomatoes-market", label: "At the market" }, { image: "tomatoes-harvest", label: "The harvest" }];
  return <section className="lp-section lp-marketplace" id="marketplace-story"><div className="lp-section-heading" data-reveal><div><SectionLabel number="08">Grown. Listed. Connected.</SectionLabel><h2>From field<br /><span className="lp-soft">to marketplace.</span></h2></div><div><p className="lp-body">Good produce deserves a closer look. Discover farmer listings, explore crop images and keep your orders in one place.</p><LandingLink to="/marketplace" secondary>Explore Marketplace</LandingLink></div></div><p className="lp-produce-disclaimer">Illustrative produce and prices · photography is not linked to a live listing.</p><div className="lp-produce-grid">{produce.map((item, index) => <Link to="/marketplace" className="lp-produce" key={item.name} data-reveal data-cursor="Explore" style={{ "--reveal-delay": `${index * 90}ms` }}><div className="lp-produce-photo"><Photo name={item.image} alt={item.alt} width="700" height="850" /><span className="lp-produce-open"><Arrow diagonal /></span><span className="lp-produce-index">0{index + 1}</span></div><div className="lp-produce-caption"><h3>{item.name}</h3><p>₹{item.price}<span> / kg</span></p></div></Link>)}</div>
    <div className="lp-gallery-story" data-reveal><div><SectionLabel>More than a cover photo</SectionLabel><h3>One crop.<br /><span className="lp-soft">Every angle.</span></h3><p>Farmers can add up to five images, preview their selection and remove an accidental photo before saving. Customers explore the complete gallery.</p><small>5 images maximum · 5 MB each<br />Stored and delivered through Cloudinary.</small></div><div className="lp-mini-gallery"><div className="lp-gallery-frame"><Photo name={views[angle].image} alt={`Illustrative tomato photo: ${views[angle].label}`} width="1000" height="670" /><span>0{angle + 1} / 03</span></div><div className="lp-gallery-controls" role="group" aria-label="Illustrative tomato gallery">{views.map((view, index) => <button key={view.image} onClick={() => setAngle(index)} aria-pressed={angle === index} aria-label={`Show tomato photo: ${view.label}`}><Photo name={view.image} alt="" width="80" height="64" /><span>{view.label}</span></button>)}</div><p className="lp-fine">Interactive gallery demonstration · independent stock photographs, not one actual listing.</p></div></div>
  </section>;
}

export function TraceabilitySection() {
  return <section className="lp-section lp-trace" id="traceability"><div className="lp-passport" data-reveal><div className="lp-passport-top"><span>AGROSPHERE</span><span>CROP PASSPORT</span></div><Photo name="tomatoes-market" alt="Tomatoes displayed for sale; illustrative crop passport" width="1000" height="660" /><div className="lp-passport-body"><div><small>INFORMATION RECORDED IN AGROSPHERE</small><h3>Tomato</h3><p>Crop · Farmer display name · General location<br />Listing date · Stock · Optional harvest date</p></div><div className="lp-scan-symbol" aria-hidden="true"><span /><span /><span /><span /><svg viewBox="0 0 80 80" fill="none"><path d="M10 20h60M10 30h60M10 40h60M10 50h60M10 60h60M20 10v60M30 10v60M40 10v60M50 10v60M60 10v60" stroke="currentColor" strokeWidth="3" /></svg></div></div><SampleLabel>Passport illustration · not a scannable QR</SampleLabel></div><div data-reveal><SectionLabel number="09">A record you can reach</SectionLabel><h2>Scan the story<br /><span className="lp-soft">behind the crop.</span></h2><p className="lp-body">Each listing gets a stable, server-generated trace ID. Its QR opens a public page with selected information recorded in AgroSphere—without requiring login.</p><div className="lp-trace-flow"><span>Scan QR</span><Arrow /><span>Public URL</span><Arrow /><span>Crop record</span></div><p className="lp-fine">Database-backed traceability, not blockchain or external certification. Information is farmer-provided; private contact details and AI history are not exposed.</p><LandingLink to="/marketplace" secondary>Discover crop listings</LandingLink></div></section>;
}
